// Generated by gencpp from file continuum/GoToResponse.msg
// DO NOT EDIT!


#ifndef CONTINUUM_MESSAGE_GOTORESPONSE_H
#define CONTINUUM_MESSAGE_GOTORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace continuum
{
template <class ContainerAllocator>
struct GoToResponse_
{
  typedef GoToResponse_<ContainerAllocator> Type;

  GoToResponse_()
    : err(0)  {
    }
  GoToResponse_(const ContainerAllocator& _alloc)
    : err(0)  {
  (void)_alloc;
    }



   typedef int32_t _err_type;
  _err_type err;





  typedef boost::shared_ptr< ::continuum::GoToResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::continuum::GoToResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoToResponse_

typedef ::continuum::GoToResponse_<std::allocator<void> > GoToResponse;

typedef boost::shared_ptr< ::continuum::GoToResponse > GoToResponsePtr;
typedef boost::shared_ptr< ::continuum::GoToResponse const> GoToResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::continuum::GoToResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::continuum::GoToResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::continuum::GoToResponse_<ContainerAllocator1> & lhs, const ::continuum::GoToResponse_<ContainerAllocator2> & rhs)
{
  return lhs.err == rhs.err;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::continuum::GoToResponse_<ContainerAllocator1> & lhs, const ::continuum::GoToResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace continuum

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::continuum::GoToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::continuum::GoToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::continuum::GoToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::continuum::GoToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::continuum::GoToResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::continuum::GoToResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::continuum::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6e094011a4dfaee5eddf447220446cf";
  }

  static const char* value(const ::continuum::GoToResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6e094011a4dfaeeULL;
  static const uint64_t static_value2 = 0x5eddf447220446cfULL;
};

template<class ContainerAllocator>
struct DataType< ::continuum::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "continuum/GoToResponse";
  }

  static const char* value(const ::continuum::GoToResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::continuum::GoToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 err\n"
;
  }

  static const char* value(const ::continuum::GoToResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::continuum::GoToResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.err);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::continuum::GoToResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::continuum::GoToResponse_<ContainerAllocator>& v)
  {
    s << indent << "err: ";
    Printer<int32_t>::stream(s, indent + "  ", v.err);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTINUUM_MESSAGE_GOTORESPONSE_H
