// Generated by gencpp from file continuum/GoTo.msg
// DO NOT EDIT!


#ifndef CONTINUUM_MESSAGE_GOTO_H
#define CONTINUUM_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <continuum/GoToRequest.h>
#include <continuum/GoToResponse.h>


namespace continuum
{

struct GoTo
{

typedef GoToRequest Request;
typedef GoToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoTo
} // namespace continuum


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::continuum::GoTo > {
  static const char* value()
  {
    return "923fa2ccf66dd81a21848e9f11aed3cd";
  }

  static const char* value(const ::continuum::GoTo&) { return value(); }
};

template<>
struct DataType< ::continuum::GoTo > {
  static const char* value()
  {
    return "continuum/GoTo";
  }

  static const char* value(const ::continuum::GoTo&) { return value(); }
};


// service_traits::MD5Sum< ::continuum::GoToRequest> should match
// service_traits::MD5Sum< ::continuum::GoTo >
template<>
struct MD5Sum< ::continuum::GoToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::continuum::GoTo >::value();
  }
  static const char* value(const ::continuum::GoToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::continuum::GoToRequest> should match
// service_traits::DataType< ::continuum::GoTo >
template<>
struct DataType< ::continuum::GoToRequest>
{
  static const char* value()
  {
    return DataType< ::continuum::GoTo >::value();
  }
  static const char* value(const ::continuum::GoToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::continuum::GoToResponse> should match
// service_traits::MD5Sum< ::continuum::GoTo >
template<>
struct MD5Sum< ::continuum::GoToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::continuum::GoTo >::value();
  }
  static const char* value(const ::continuum::GoToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::continuum::GoToResponse> should match
// service_traits::DataType< ::continuum::GoTo >
template<>
struct DataType< ::continuum::GoToResponse>
{
  static const char* value()
  {
    return DataType< ::continuum::GoTo >::value();
  }
  static const char* value(const ::continuum::GoToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTINUUM_MESSAGE_GOTO_H
