// Generated by gencpp from file continuum/MotorStates.msg
// DO NOT EDIT!


#ifndef CONTINUUM_MESSAGE_MOTORSTATES_H
#define CONTINUUM_MESSAGE_MOTORSTATES_H

#include <ros/service_traits.h>


#include <continuum/MotorStatesRequest.h>
#include <continuum/MotorStatesResponse.h>


namespace continuum
{

struct MotorStates
{

typedef MotorStatesRequest Request;
typedef MotorStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorStates
} // namespace continuum


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::continuum::MotorStates > {
  static const char* value()
  {
    return "234b96902b9e5908267e7e3b9c5ca30f";
  }

  static const char* value(const ::continuum::MotorStates&) { return value(); }
};

template<>
struct DataType< ::continuum::MotorStates > {
  static const char* value()
  {
    return "continuum/MotorStates";
  }

  static const char* value(const ::continuum::MotorStates&) { return value(); }
};


// service_traits::MD5Sum< ::continuum::MotorStatesRequest> should match
// service_traits::MD5Sum< ::continuum::MotorStates >
template<>
struct MD5Sum< ::continuum::MotorStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::continuum::MotorStates >::value();
  }
  static const char* value(const ::continuum::MotorStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::continuum::MotorStatesRequest> should match
// service_traits::DataType< ::continuum::MotorStates >
template<>
struct DataType< ::continuum::MotorStatesRequest>
{
  static const char* value()
  {
    return DataType< ::continuum::MotorStates >::value();
  }
  static const char* value(const ::continuum::MotorStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::continuum::MotorStatesResponse> should match
// service_traits::MD5Sum< ::continuum::MotorStates >
template<>
struct MD5Sum< ::continuum::MotorStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::continuum::MotorStates >::value();
  }
  static const char* value(const ::continuum::MotorStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::continuum::MotorStatesResponse> should match
// service_traits::DataType< ::continuum::MotorStates >
template<>
struct DataType< ::continuum::MotorStatesResponse>
{
  static const char* value()
  {
    return DataType< ::continuum::MotorStates >::value();
  }
  static const char* value(const ::continuum::MotorStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTINUUM_MESSAGE_MOTORSTATES_H
