// Generated by gencpp from file continuum/Reset.msg
// DO NOT EDIT!


#ifndef CONTINUUM_MESSAGE_RESET_H
#define CONTINUUM_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <continuum/ResetRequest.h>
#include <continuum/ResetResponse.h>


namespace continuum
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace continuum


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::continuum::Reset > {
  static const char* value()
  {
    return "b6e094011a4dfaee5eddf447220446cf";
  }

  static const char* value(const ::continuum::Reset&) { return value(); }
};

template<>
struct DataType< ::continuum::Reset > {
  static const char* value()
  {
    return "continuum/Reset";
  }

  static const char* value(const ::continuum::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::continuum::ResetRequest> should match
// service_traits::MD5Sum< ::continuum::Reset >
template<>
struct MD5Sum< ::continuum::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::continuum::Reset >::value();
  }
  static const char* value(const ::continuum::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::continuum::ResetRequest> should match
// service_traits::DataType< ::continuum::Reset >
template<>
struct DataType< ::continuum::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::continuum::Reset >::value();
  }
  static const char* value(const ::continuum::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::continuum::ResetResponse> should match
// service_traits::MD5Sum< ::continuum::Reset >
template<>
struct MD5Sum< ::continuum::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::continuum::Reset >::value();
  }
  static const char* value(const ::continuum::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::continuum::ResetResponse> should match
// service_traits::DataType< ::continuum::Reset >
template<>
struct DataType< ::continuum::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::continuum::Reset >::value();
  }
  static const char* value(const ::continuum::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTINUUM_MESSAGE_RESET_H
